### ISSUE TITLE
[LOG] Добавить логгирование

### ISSUE THREAD

**Issue by anry-das** [argosumy/RestServise#2]
Необходимо добавить логгирование и заменить
`e.printStackTrace();`
на вызов логгера

**Comment by argosumy** [comment]
Исправил
https://github.com/argosumy/RestServise/commit/bf93c92dc30336b8e65a8a6a49b0be16d54b004b

**Comment by anry-das** [comment]
в WordDoc еще есть e.printStackTrace();

**Comment by argosumy** [comment]
Привет.Подправил.


чт, 14 мая 2020 г. в 11:21, Andrey Denysenko <notifications@github.com>:
