### ISSUE TITLE
[APP] Не реализовано xml / json форматы ответа

### ISSUE THREAD

**Issue by anry-das** [argosumy/RestServise#4]
В приложении не реализовано требование по наличию xml / json форматов выдачи результата

Тут также необходимо будет добавить конфигурацию.

**Основное - контроллер не должен возвращать строку!**

**Comment by argosumy** [comment]
Исправлена
https://github.com/argosumy/RestServise/commit/05fa1801d9736b37cd246681b4197cda29bb8494
