### ISSUE TITLE
[ExchangeRatesSearchIn] Неправильная реализация

### ISSUE THREAD

**Issue by anry-das** [argosumy/RestServise#7]
Использование интерфейсов подразумевает, что они будут имплементированы в нескольких классах.
Необходимо для каждого банка сделать свою имплементацию, а в контроллере создавать список  таких имплементаций и уже его использовать для общения с банком, а не одну имплементацию как сейчас.

**Comment by argosumy** [comment]
Исправлена
https://github.com/argosumy/RestServise/commit/05fa1801d9736b37cd246681b4197cda29bb8494
