### ISSUE TITLE
[APP] Использовать UriComponentsBuilder

### ISSUE THREAD

**Issue by anry-das** [argosumy/RestServise#9]
Для создания URL с параметрами можно использовать UriComponentsBuilder

**Comment by argosumy** [comment]
исправил
https://github.com/argosumy/RestServise/commit/52a9130bf7cdabd31b70b11dc0738f4369c28de7

**Comment by argosumy** [comment]
Привет. Все твои замечания исправил.

вт, 5 мая 2020 г. в 11:35, Andrey Denysenko <notifications@github.com>:

**Comment by anry-das** [comment]
можно еще тикеты позакрывать

**Comment by argosumy** [comment]
Тикеты закрыл.

чт, 14 мая 2020 г. в 10:24, Andrey Denysenko <notifications@github.com>:
